### ROLE_MANAGER adding a new ROLE_USER (user to use in next requests)
POST http://localhost:5353/customers
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "full_name":"Bo Hua",
    "nric":"S5002946H",
    "phone":"91251235",
    "address":"27 Jalan Alamak S6802342",
    "username":"goodusers2",
    "password":"Ilovewonton2",
    "authorities":"ROLE_USER",
    "active": true
}

### ROLE_MANAGER adding a new content (1)
POST http://localhost:5353/contents
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "title":"Spring Security Fundamentals",
    "summary":"summary",
    "content": "content",
    "link":"link1234567890",
    "approved": true
}

### ROLE_MANAGER adding a new content (2)
POST http://localhost:5353/contents
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "title":"Gone With The Wind",
    "summary":"summary",
    "content": "content",
    "link":"link12345",
    "approved": false
}

### ROLE_MANAGER get all contents (both approved and unapproved)
GET http://localhost:5353/contents
Authorization: Basic manager_1 01_manager_01

### ROLE_MANAGER getting content with specified id
GET http://localhost:5353/contents/1
Authorization: Basic manager_1 01_manager_01

### ROLE_MANAGER getting content with un-existent specified id
GET http://localhost:5353/contents/3
Authorization: Basic manager_1 01_manager_01

### ROLE_USER only getting approved contents
GET http://localhost:5353/contents
Authorization: Basic goodusers2 Ilovewonton2

### ROLE_MANAGER deletes content with specified id
DELETE http://localhost:5353/contents/1
Authorization: Basic manager_1 01_manager_01

### ROLE_MANAGER get all contents
GET http://localhost:5353/contents
Authorization: Basic manager_1 01_manager_01 

### ROLE_MANAGER adding a new content (3)
POST http://localhost:5353/contents
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "title":"The title of the advisory or news by manager haha",
    "summary":"The short summary of the content item",
    "content": "The text of the content item",
    "link":"https://link.to.externalcontent",
    "approved": false
}

### ROLE_USER unable to get an unapproved content with specified id
GET http://localhost:5353/contents/3
Authorization: Basic goodusers2 Ilovewonton2

### ROLE_MANAGER updates an existing content
PUT http://localhost:5353/contents/2
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "title":"The title of the advisory or news by manager",
    "summary":"The short summary of the content item",
    "content": "This is a new content by manager",
    "link":"https://link.to.externalcontent",
    "approved": false
}

### ROLE_ANALYST adding a new content (unapproved)
POST http://localhost:5353/contents
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01

{
    "title":"The new title",
    "summary":"The short summary of the content item",
    "content": "The text of the content item",
    "link":"https://link.to.externalcontent",
    "approved": false
}

### ROLE_ANALYST unable to approve an existing content
PUT http://localhost:5353/contents/2
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01

{
    "title":"The new title",
    "summary":"The short summary of the content item",
    "content": "The text of the content item",
    "link":"https://link.to.externalcontent",
    "approved": true
}